spring.application.name=payment-service
server.port=${PAYMENT_SERVICE_PORT:8086}

spring.datasource.url=${PAYMENT_DB_URL:jdbc:h2:file:./data/watch_payment_db;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH}
spring.datasource.username=${H2_USER:sa}
spring.datasource.password=${H2_PASSWORD:}
spring.datasource.driver-class-name=org.h2.Driver
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false

axon.axonserver.servers=${AXON_SERVER_SERVERS:127.0.0.1:8124}
axon.serializer.general=jackson
axon.serializer.events=jackson
axon.serializer.messages=jackson

app.security.internal-token=${INTERNAL_TOKEN:dev-internal-token}
app.security.jwt-secret=${JWT_SECRET:MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY=}

app.payos.api-url=${PAYOS_API_URL:https://api-merchant.payos.vn}
app.payos.client-id=${PAYOS_CLIENT_ID:}
app.payos.api-key=${PAYOS_API_KEY:}
app.payos.checksum-key=${PAYOS_CHECKSUM_KEY:}
app.payos.return-url=${PAYOS_RETURN_URL:http://localhost:8080/api/payments/payos/return}
app.payos.cancel-url=${PAYOS_CANCEL_URL:http://localhost:8080/api/payments/payos/cancel}
app.frontend.home-url=${FRONTEND_HOME_URL:http://localhost:4200/home}
app.payment.expire-minutes=${PAYMENT_EXPIRE_MINUTES:10}
app.payment.expire-scan-delay-ms=${PAYMENT_EXPIRE_SCAN_DELAY_MS:10000}
eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka}
