spring.application.name=payment-service
server.port=${PAYMENT_SERVICE_PORT:8086}

spring.datasource.url=${PAYMENT_DB_URL:jdbc:h2:file:./data/watch_payment_db;DATABASE_TO_LOWER=TRUE;INIT=CREATE SCHEMA IF NOT EXISTS public}
spring.datasource.username=${H2_USER:sa}
spring.datasource.password=${H2_PASSWORD:}
spring.datasource.driver-class-name=org.h2.Driver
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false

axon.axonserver.servers=${AXON_SERVER_SERVERS:127.0.0.1:8124}
axon.serializer.general=jackson
axon.serializer.events=jackson
axon.serializer.messages=jackson

app.security.internal-token=${INTERNAL_TOKEN:dev-internal-token}
app.security.jwt-secret=${JWT_SECRET:MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY=}

app.payos.api-url=${PAYOS_API_URL:https://api-merchant.payos.vn}
app.payos.client-id=${PAYOS_CLIENT_ID:4e8920a2-a525-4a3e-8f61-d8ec3aa515c6}
app.payos.api-key=${PAYOS_API_KEY:06ecfb0d-ee07-499e-826d-4f8a37c53b78}
app.payos.checksum-key=${PAYOS_CHECKSUM_KEY:8132a3e88ecfb4e8eba7f904128d250233a6aa4aeae11b2327f80c1ebc1c9b1f}
app.payos.return-url=${PAYOS_RETURN_URL:http://localhost:8080/api/payments/payos/return}
app.payos.cancel-url=${PAYOS_CANCEL_URL:http://localhost:8080/api/payments/payos/cancel}
app.frontend.home-url=${FRONTEND_HOME_URL:http://localhost:4200/home}
app.payment.expire-minutes=${PAYMENT_EXPIRE_MINUTES:15}
eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka}
