server:
  port: 8090

spring:
  application:
    name: admin-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: admin-service
  mail:
    host: localhost
    port: 1025

app:
  security:
    jwt-secret: ${JWT_SECRET:MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY=}

axon:
  axonserver:
    servers: localhost:8124
    client-id: admin-service
    component-name: admin-service
  serializer:
    general: jackson
    messages: jackson

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

resilience4j:
  circuitbreaker:
    instances:
      productService:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
      inventoryService:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
  timelimiter:
    instances:
      productService:
        timeout-duration: 3s
      inventoryService:
        timeout-duration: 3s
