server.port=8090

spring.application.name=admin-service
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=admin-service
spring.mail.host=localhost
spring.mail.port=1025

app.security.jwt-secret=${JWT_SECRET:MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY=}

axon.axonserver.servers=localhost:8124
axon.axonserver.client-id=admin-service
axon.axonserver.component-name=admin-service
axon.serializer.general=jackson
axon.serializer.messages=jackson

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

resilience4j.circuitbreaker.instances.productService.sliding-window-size=10
resilience4j.circuitbreaker.instances.productService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.productService.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.productService.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.inventoryService.sliding-window-size=10
resilience4j.circuitbreaker.instances.inventoryService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.inventoryService.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.inventoryService.permitted-number-of-calls-in-half-open-state=3
resilience4j.timelimiter.instances.productService.timeout-duration=3s
resilience4j.timelimiter.instances.inventoryService.timeout-duration=3s
