spring.application.name=notificationservice
server.port=9004
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.consumer.group-id=${KAFKA_GROUP_ID:notificationservice}
app.kafka.topics.email-verification=${EMAIL_VERIFICATION_TOPIC:email-verification}

spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:huynhvangiang0504@gmail.com}
spring.mail.password=${MAIL_PASSWORD:eljt iwyq uuri uoek}
spring.mail.properties.mail.smtp.auth=${MAIL_SMTP_AUTH:true}
spring.mail.properties.mail.smtp.starttls.enable=${MAIL_SMTP_STARTTLS_ENABLE:true}
spring.mail.properties.mail.transport.protocol=smtp

app.frontend.login-url=${FRONTEND_LOGIN_URL:http://localhost:4200/login}
axon.axonserver.servers=${AXON_SERVER_SERVERS:localhost:8124}
